name: Pull Request
on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create env file
        run: |
          touch .env
          echo CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_PROJECT_TOKEN }} >> .env
          echo SONGS_API_KEY=${{ secrets.SONGS_API_KEY }} >> .env
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,build,test

      - name: Build storybook
        run: npx nx run shared-ui:build-storybook
        if: ${{ github.actor == 'dankreiger' }}
      - name: Deploy chromatic
        run: npx nx run shared-ui:deploy-storybook
        if: ${{ github.actor == 'dankreiger' }}
